config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  devise_for :users, :controllers => { :registrations => :registrations } 
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users do
    resources :posts
  end
  resources :projects 
  resources :tasks do 
    member do
      put 'toggle_completed'
    end
  end

  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
      get "requests", :on => :collection
      get "invites", :on => :collection
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   include Amistad::FriendModel

   has_many :posts, dependent: :destroy
   has_many :projects, dependent: :destroy
   has_many :tasks, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :quote, :password, :password_confirmation) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:firstname, :lastname, :email, :quote, :current_password) }
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	before_filter :authenticate_user!

  def index
    @friends = current_user.friends
  end

  def new
    @users = User.all
  end

  def create
    invitee = User.find_by_id(params[:user_id])
    if current_user.invite invitee
      redirect_to root_path, :notice => "Successfully invited friend!"
    else
      redirect_to root_path, :notice => "Sorry! You can't invite that user!"
    end
  end

  def update
    inviter = User.find_by_id(params[:id])
    if current_user.approve inviter
      redirect_to root_path, :notice => "Successfully confirmed friend!"
    else
      redirect_to root_path, :notice => "Sorry! Could not confirm friend!"
    end
  end

  def requests
    @pending_requests = current_user.pending_invited_by
  end

  def invites
    @pending_invites = current_user.pending_invited
  end

  def destroy
    user = User.find_by_id(params[:id])
    if current_user.remove_friendship user
      redirect_to friends_path, :notice => "Successfully removed friend!"
    else
      redirect_to friends_path, :notice => "Sorry, couldn't remove friend!"
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end
	def new
		@user = current_user
		@post = @user.posts.create
	end

	def create
		@user = current_user
		@post = @user.posts.create(post_params)
		if @post.save
			redirect_to root_path
		end
	end

	def show
		@user = current_user
		@post = Post.find(params[:id])
		@author = User.where({id: @post.user_id})
		
	end

	def update

	end
	def destroy
		Post.find(params[:id]).destroy
		redirect_to root_path
	end

	private 
	def post_params
		params.require(:post).permit(:title, :content, :post_type)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


	def create
		@user = current_user
		@project = @user.projects.create(project_params)
		if @project.save
			redirect_to root_path
		else
			redirect_to user_path(current_user)
		end
	end

	def destroy
		Project.find(params[:id]).destroy
		redirect_to root_path
	end

	private 
	def project_params
		params.require(:project).permit(:title, :completed)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
      user_path(resource)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create 
		@task = current_user.tasks.build(task_params)

		if @task.save
      		flash[:success] ="Added!"
     		redirect_to root_path
     	end

	end

	def destroy
		Task.find(params[:id]).destroy
		redirect_to root_path
	end

	def toggle_completed
		@task = Task.find(params[:id])
		@task.completed = !@task.completed
		@task.save
		redirect_to :back
	end

	 private
    def task_params
      params.require(:task).permit(:project_id, :content, :completed)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@post = @user.posts.new
		@posts = @user.posts	
		@users = User.all
		
		@friends = current_user.friends
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

		@user = current_user
		if user_signed_in?
			
			@friends = current_user.friends
			
			
			@announcements = @user.posts.where({post_type: 1}) + Post.where(:user_id => current_user.friends, post_type: 1)
			@announcements.sort! { |a, b| b.created_at <=> a.created_at }  
			@compliments = @user.posts.where({post_type: 2}) + Post.where(:user_id => current_user.friends, post_type: 2)
			@compliments.sort! { |a, b| b.created_at <=> a.created_at } 
			

			@users = User.all
			

		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_friendpopover.html.erb
<div class = "hidden-sm hidden-md hidden-lg">
  <% if user_signed_in? %>
            <div id="popover-wrap">
              
            <button class = "btn navbar-btn btn-warning" id="popoverFriends" data-placement = "bottom" data-trigger="focus">W.P.A. <span class="badge"><%= @user.pending_invited_by.count %></span></button>
                <div id="popoverFriendsHiddenContent" style="display: none">
                  

                   <% unless @user.pending_invited_by.empty? %>
              <% @user.pending_invited_by.each do |u| %>
                <h3 class="text-center"><%= link_to u.firstname, user_path(u.id) %>
              <%= link_to "Confirm friend?", friend_path(u), :method => "put" %> 
              
              <% end %>
            <% else %>
            None :(
            <% end %>
            </h3>
                </div>  
                
                <div id="popoverFriendsHiddenTitle" style="display: none">
                   <h3>Your requests: </h3>
                </div> 
             </div>
             <% end %>
              </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knopebook</title>
  
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag 'custom' %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Londrina+Sketch' rel='stylesheet' type='text/css'>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "KnopeBook", root_path, class: "navbar-brand" %>
        
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div>
      
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
      	<%  unless user_signed_in? %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <% else %>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => 'delete' %></li>

        
        <li>
            <div id="popover-wrap">
              
            <button class = "btn navbar-btn btn-warning" id="popoverFriends" data-placement = "bottom" data-trigger="focus">Workplace Proximity Acquaintances <span class="badge"><%= @user.pending_invited_by.count %></span></button>
                <div id="popoverFriendsHiddenContent" style="display: none">
                  

                   <% unless @user.pending_invited_by.empty? %>
              <% @user.pending_invited_by.each do |u| %>
                <h3 class="text-center"><%= link_to u.firstname, user_path(u.id) %>
              <%= link_to "Confirm friend?", friend_path(u), :method => "put" %> 
              
              <% end %>
            <% else %>
            None :(
            <% end %>
            </h3>
                </div>  
                
                <div id="popoverFriendsHiddenTitle" style="display: none">
                   <h3>Your requests: </h3>
                </div> 
             </div>
              </li>
        <li><button class = "btn navbar-btn">Button</button></li>
        <li><button type="button" class="btn navbar-btn" data-toggle="modal" data-target="#myModal">
 						 Profile
						</button>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	
		<%= yield %>
		
	<div class = "navbar navbar-default navbar-fixed-bottom">
		<p class = "navbar-text"><span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> Chris Lange 2015 </p>
	</div>
  <% if user_signed_in? %>
      <!-- Profile Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Hey <%= current_user.firstname %>!</h4>
          </div>
          <div class="modal-body">
           <p> Name: <%= current_user.firstname + " " + current_user.lastname %> </p>
            <p>Email: <%= current_user.email %> </p>
            <p>Quote: <%= current_user.quote %></p>
            <p> Position at Parks and Recreation: </p>
            <p> Score on Big Game Hunters: </p>



          </div>
          <div class="modal-footer">
            <button type="button" class="btn" data-dismiss="modal">Close</button>
            <%= link_to "Edit", edit_user_registration_path(@user), class: "btn btn-warning" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</body>
</html>

app/views/posts/_post.html.erb
	<div class = "post">
		<p class = "post_title">
			<% if !post.created_at.blank? %>  
				
			<% end %>
		</p>
		<p class = "post_content">
			<% if !post.content.blank? %>
				<%= post.content %>
			<% end %>
		</p>
	</div>
	<div class = "post-head pull-right">
		<strong > <%= post.created_at.strftime("%b %e, %Y") %> by <%= link_to post.user.firstname, user_path(post.user) %> </strong>
		<% if post.user == current_user %>
					| <%= link_to [@user, post], method: :delete, data: { confirm: "You sure?" }, class: "text-right" do %> 
						<i class="glyphicon glyphicon-remove"></i>
					<% end %>
				<%end%>
	</div>

<hr>

app/views/projects/_project.html.erb
<div class = "col-xs-11">
	<div class = "post">
		<p><strong><%= project.title %> 
			<%= link_to project, method: :delete, data: { confirm: "You sure?" }, class: "text-right pull-right" do %>
				<i class="glyphicon glyphicon-remove"></i>
			<% end %>
		</p></strong>

		<%= render project.tasks %>
		<hr>
		<%= render 'tasks/task_form', project: project %>

	</div>
</div>
<div class = "col-xs-1 flag">
	
</div>

app/views/tasks/_task.html.erb
<li><span>
	<% if task.completed %>
		<del><%= task.content %> </del>
	<% else %>
		<%= task.content %>
	<% end %>
	<span>
	<%= link_to toggle_completed_task_path(task), :method => :put, class: "checkbutton" do %>
		<i class="glyphicon glyphicon-ok"></i>
	<% end %>
	<%= link_to task, method: :delete, data: { confirm: "You sure?" }, class: "text-right float-right" do %>
		<i class="glyphicon glyphicon-remove"></i>
	<% end %>
</li>

app/views/tasks/_task_form.html.erb
<%= form_for(project.tasks.build) do |f| %>
  <%= f.hidden_field :project_id %>
  <div class = "input-group">
  	<span class="input-group-addon" id="basic-addon1"><i class="glyphicon glyphicon-pencil"></i></span>
    <%= f.text_field :content, 'aria-describedby' => "basic-addon1", id: "todofield", class: "form-control" %>
  	<span class="input-group-btn">
  		<%= button_tag(type: 'submit', class: "btn btn-warning") do %>
 		<i class="glyphicon glyphicon-plus"></i>
		<% end %>
	</span>
  </div>
<% end %>

app/views/users/show.html.erb
<div class = "container">
	<div class = "content">
		<div class = "content-wrapper">
			<div class = "row">
				<div class = "col-md-3">
					<div class = "jumbotron">
						<h1><span class="glyphicon glyphicon-picture" aria-hidden="true"></span></h1>
					</div>
				</div>
				<div class = "col-md-9">
					<div class = "jumbotron">
						<h1>
							<%= @user.firstname.titleize %> <small><%= @user.lastname %></small>
							
							</h1>
						<%= link_to "Edit", edit_user_registration_path(@user), class: "btn btn-warning" %>

					</div>
				</div>
			</div>
			<hr>
			<div class = "row">
				<div class = "col-md-2">
					<% @users.each do |user| %>
						<% if user != current_user %>
							<% if !user.friend_with? current_user  %>
								<p><%= user.firstname %></p>
								<%= link_to "Add friend?", friends_path(:user_id => user), :method => "post" %>
							<% end %>
						<% end %>
					<% end %>
					<% current_user.pending_invited_by.each do |user| %>
						<%= user.firstname %> <% link_to "Confirm friend?", friend_path(user), :method => "put" %>
					<% end %>
				</div>
				<div class = "col-md-2">
					Your friends: <hr>
					<% @user.friends.each do |friend| %>
						<p><%= friend.firstname %> </p>
					<% end %>
				</div>
				<div class = "col-md-8">
					<div class = "row">
						<div class = "col-xs-4">
							<div class = "post">
								<h5>Favorite MouseRat Song</h5>
								<h4>10,000 candles in the wind </h4>
							</div>
						</div>
						<div class = "col-xs-4">
							<div class = "post">
								<h5>Big Game Hunter Score</h5>
								<h4>9,500 </h4>
							</div>
						</div>
						<div class = "col-xs-4">
							<div class = "post">
								<h5>Favorite Female Senetor</h5>
								<h4>Maria Cantwell</h4>
							</div>
						</div>
					</div>
					<div class = "row">
						<div class = "col-xs-12">
							<div class = "post">
								<h5> Quote </h5>
								<h2><%= @user.quote %> </h2>
							</div>
						</div>
					</div>
					<div class = "row">
						<div class = "col-xs-4">
							<div class = "post">
							</div>
						</div>
						<div class = "col-xs-4">
							<div class = "post">
							</div>
						</div>
						<div class = "col-xs-4">
							<div class = "post">
							</div>
						</div>
					</div>

				</div>
			</div> 
		</div> <!-- content-wrapper -->
	</div>
</div> <!-- container -->

app/views/welcome/_announcement_form.html.erb
<div class = "form-group">
	<%= form_for [@user, Post.new] do |f| %> 
	<div class = "input-group">
		<span class="input-group-addon" id="basic-addon1"><i class="glyphicon glyphicon-pencil"></i></span>
		<%= f.text_area :content, class: 'form-control', 'aria-describedby' => "basic-addon1" , placeholder: 'Rectangle. America. Megaphone. Monday. Butthole.' %>
	</div>
	<%= f.hidden_field :post_type, :value => 1 %>
</div> <!-- form group-->

<p class = "text-center"><%= f.submit class: 'btn btn-warning' %> </p>

	<% end %>

app/views/welcome/_compliment_form.html.erb
<div class="form-group">
    <%= form_for [@user, Post.new] do |f| %>
    <h2 class = "text-center"><%= f.label "Anne you" %></h2>
      <select class="input-group form-control" id = "comp-val1">
          <option>beautiful</option>
          <option>wonderful</option>
          <option>opulent</option>
      </select>
      <select class="input-group form-control" id = "comp-val2">
        <option>tropical</option>
        <option>gay</option>
        <option>harmonious</option>
      </select>
      <select class="input-group form-control" id = "comp-val3">
        <option>fish</option>
        <option>penguin</option>
        <option>musk-Ox</option>
      </select>
      </div>
      <%= f.hidden_field :content, :id => "comp-result" , :value => "Testing" %>
      <%= f.hidden_field :post_type, :value => 2 %>
      <p class = "text-center"><%= f.submit "Compliment", class: 'btn btn-warning', id: 'comp-button' %></p>
    <% end %>

app/views/welcome/_project_form.html.erb
<div class = "form-group">
<%= form_for Project.new do |f| %> 
		<div class = "input-group">
			<span class="input-group-addon" id="basic-addon1"><i class="glyphicon glyphicon-pencil"></i></span>
			<%= f.text_field :title, class: 'form-control', 'aria-describedby' => "basic-addon1", placeholder: 'The Pawnee Commons' %>	
		</div>
	</div> <!-- form group-->

<p class = "text-center"><%= f.submit class: 'btn btn-warning' %> </p>

	<% end %>

app/views/welcome/index.html.erb
<div class = "container-fluid">
	<% if user_signed_in? %>
	<div class = "content">
		</div>
	<div class = "content-wrapper">
		<div class = "row top-row">
			<div class = "col-md-4">
				<div class = "post text-center">
					<h1><span class="glyphicon glyphicon-bullhorn giant-glyph" aria-hidden="true"></span></h1>
					<h4>Make an announcement</h4>
				</div>
				<%= render "welcome/announcement_form" %>
					
			</div>
			<div class = "col-md-4">
				<div class = "post text-center">
					<h1><span class="glyphicon glyphicon-heart-empty giant-glyph" aria-hidden="true"></span></h1>
					<h4>Compliment Anne</h4>
				</div>
				<%= render "welcome/compliment_form" %>	
			</div>
			<div class = "col-md-4">
				<div class = "post text-center">
					<h1><span class="glyphicon glyphicon-tasks giant-glyph" aria-hidden="true"></span></h1>
					<h4>Start a project</h4>
				</div>
				<%= render "welcome/project_form" %>	
			</div>

		</div>
	
	<hr>
		<div class = "row ">
			<div class = "col-md-4" >
				
					<h2 class = "text-center"> Latest announcements </h2>
					<% @announcements.each_slice(3) do |announcements| %>
						 <%= render partial: "posts/post", collection: announcements %>
							<div class = "post">
								<%= image_tag "ParksAndRecAds1"  %>
							</div>
					<% end %>
				
			</div>
			<div class = "col-md-4" style = 'background-color: rgba(0, 0, 0, 0.03);'>

				<h2 class = "text-center"> Newest compliments </h2>
				<%= render @compliments %>
			</div>
			<div class = "col-md-4">
				<div class = "row">
					<h2 class = "text-center"> Current projects </h2>
					<%= render @user.projects %>
				</div>
			</div>
		</div><!-- row -->
	</div> <!-- content-wrapper -->
	<% else %>

	<div class = "login-wrapper">
		<div class = "login-inner">
			<h1 class = "login-hero">Be the Leslie Knope of whatever you do!</h1>
			
			<h3> <%= link_to "Log in" , new_user_session_path %> or <%= link_to "Sign up" , new_user_registration_path %> and help make Pawnee great </h3>
		</div>
	</div>
	<% end %>



</div> <!-- contrainer-fluid -->